#' Create a list to configure \href{https://datatables.net/extensions/buttons/}{Datatable Buttons extension} options
#' \href{https://datatables.net/extensions/buttons/examples/styling/icons.html}{The Icons page} demonstrates the structure of the Buttons extended options
#' @param extend \code{chr} The button type to extend
#' @param text \code{chr} Button text
#' @param icon \code{chr/shiny.tag} A `shiny.tag` generated by \link[shiny]{icon} or a character naming an icon
#' @param class \code{chr} Classes to append to the button text or icon
#' @param ... \code{additional named options}
#'
#' @return \code{list} formatted for consumption by DT
#' @export
#'
#' @examples
#' # An HTML 5 Copy button with the FontAwesome copy icon
#' datatable_button_extend(
#' 'copyHtml5',
#' text = "Copy Visible",
#' icon = "copy"
#' )
DT_button_extend <- function(extend, text, icon = NULL, class = NULL, ...) {

  icon <- if (inherits(icon, "shiny.tag")) {
    icon
  } else if (is.character(icon)) {
    shiny::icon(icon)
  }


  text <- if (!is.null(icon)) {
    icon <- htmltools::tagAppendAttributes(icon, class = paste("inline-block", class))
    tagList(icon, paste0(" ", text))
  } else {
    tags$span(class = class, text)
  }

  list(
    extend = extend,
    text = stringr::str_remove_all(htmltools::doRenderTags(text, indent = FALSE), "\\n") |> stringr::str_replace_all("\"", "'"),
    ...
  )

}
