#' Custom \code{\link[DT]{datatable}} callback Javascript
#'
#' @param ... \code{chr} arbitrary character strings to add as JS
#' @param search_icon \code{lgl} Whether to replace the "Search:" on the search field with a FontAwesome magnifying class symbol. Requires FontAwesome (typically included in shiny).
#' @param page_input \code{lgl} Whether to include a custom Shiny input that saves the page number as `input$[table output id]_page`.
#' @param pageLength_input \code{lgl} Whether to include a custom Shiny input that saves the pageLength as `input$[table output id]_pageLength`.
#' @param filter_placeholders \code{lgl} Whether to replace the Filter column placeholders using JS function `dt_filter_placeholders`
#' @param retain_policy_color \code{lgl} Whether to retain the color of the Policy ID column.
#' @param retain_selections \code{lgl} Whether to retain the selections from the previous render of the table
#' @param tab_accessible \code{lgl} Whether to enable row selection by pressing the `Enter` key. Requires `extensions = 'KeyTables'` with `options = list(keys = TRUE)`. Sets a jQuery event listener which doesn't need to be re-established on table redraw.
#' @param debugger \code{lgl} Whether to insert a debugger statement in the callback function
#' @details To preserve the page number, a custom shiny input must be set at the end of the DT render function, followed by an observer on the page input that uses \code{\link[DT]{selectPage}} to update the page via \code{\link[DT]{dataTableProxy}}. To preserve the pageLength, the page length input must be passed as the pageLength option to the DT call with the following pattern \code{shiny::isolate(`input$[table output id]_pageLength`) %||% [default value]} where default value is just the default pageLength you wish to supply in the event the pageLength is NULL.
#' @return \code{chr/JS_EVAL} Generated by \code{\link[DT]{JS}}
#' @export
#'

DT_callback <- function(..., search_icon = TRUE, page_input = TRUE, pageLength_input = TRUE, filter_placeholders = TRUE, retain_policy_color = TRUE, retain_selections = TRUE, tab_accessible = FALSE, debugger = FALSE) {

  table_id <- "table.table().node().id"
  shiny_id <- UU::glue_js("$('#' + *{table_id}*).parent().parent().attr('id')")
  out <- UU::glue_js(c("var id = *{shiny_id}*;
                       var render_id = id + '_rendered';
                       window[render_id] = window[render_id] || 0;
           Shiny.setInputValue(id + '_rendered', window[render_id], {priority: 'event'});
           Shiny.setInputValue(*{shiny_id}* + '_page', table.page() + 1, {priority: 'event'});"))
  if (debugger) {
    out <- c(out, "debugger;")
  }
  if (page_input) {
    out <- c(out, UU::glue_js("table.on('page.dt', () => {
          Shiny.setInputValue(*{shiny_id}* + '_page', table.page() + 1, {priority: 'event'});
          return table.page();
          });"))
  }
  lines <- c(paste0("var id = ", table_id, ";"), "var table_api = $(id).DataTable()")

  retain_on_draw <- c(
    "search_icon",
    "filter_placeholders",
    "retain_policy_color"
  )
  features <-
    rlang::env_get_list(
      environment(),
      nms = c(
        "search_icon",
        "filter_placeholders",
        "retain_policy_color",
        "tab_accessible"
      )
    )
  feature_nms <- names(features)
  for (i in seq_along(features)) {
    if (features[[i]]) {
      call <- glue::glue("dt_{feature_nms[i]}(id);")
      if (feature_nms[i] %in% retain_on_draw) {
        # Set placeholders on raw event listener
        lines <- c(lines, call)
      }
      # Set placeholders on initial render
      out <- c(out, call)
    }
  }

  if (!retain_selections) {
    lines <- c(lines, "table_api.rows().deselect();")
  }
  out <- c(out, UU::glue_js("
       table.on('draw.dt', () => {
         *{glue::glue_collapse(lines, sep = '\n')}*
       })")
  )


  if (pageLength_input) {
    out <- c(out,
             UU::glue_js("table.on('length.dt', (e, settings, len) => {
               Shiny.setInputValue(*{shiny_id}* + '_pageLength', len, {priority: 'event'});
             })")
             )
  }
  out <- c(out, purrr::list_c(rlang::dots_list(...), ptype = character()))
  return(DT::JS(c(out, "return table;")))
}
