#' Custom \code{\link[DT]{datatable}} callback Javascript
#'
#' @param ... \code{chr} arbitrary character strings to add as JS
#' @param search_icon \code{lgl} Whether to replace the "Search:" on the search field with a FontAwesome magnifying class symbol. Requires FontAwesome (typically included in shiny).
#' @param page_input \code{lgl} Whether to include a custom Shiny input that saves the page number as `input$[table output id]_page`.
#' @param pageLength_input \code{lgl} Whether to include a custom Shiny input that saves the pageLength as `input$[table output id]_pageLength`.
#' @param filter_placeholders \code{lgl} Whether to replace the Filter column placeholders using JS function `dt_filter_placeholders`
#' @param retain_color \code{lgl} Whether to retain the color of a column. Requires value for `retain_color_class`
#' @param retain_color_class \code{chr} The class of the `td` elements to retain the color on.
#' @param retain_selections \code{lgl} Whether to retain the selections from the previous render of the table
#' @param tab_accessible \code{lgl} Whether to enable row selection by pressing the `Enter` key. Requires `extensions = 'KeyTables'` with `options = list(keys = TRUE)`. Sets a jQuery event listener which doesn't need to be re-established on table redraw.
#' @param debugger \code{lgl} Whether to insert a debugger statement in the callback function
#' @details To preserve the page number, a custom shiny input must be set at the end of the DT render function, followed by an observer on the page input that uses \code{\link[DT]{selectPage}} to update the page via \code{\link[DT]{dataTableProxy}}. To preserve the pageLength, the page length input must be passed as the pageLength option to the DT call with the following pattern \code{shiny::isolate(`input$[table output id]_pageLength`) %||% [default value]} where default value is just the default pageLength you wish to supply in the event the pageLength is NULL.
#' @return \code{chr/JS_EVAL} Generated by \code{\link[DT]{JS}}
#' @export
#'

DT_callback <- function(..., search_icon = TRUE, page_input = TRUE, pageLength_input = TRUE, filter_placeholders = TRUE, retain_color = TRUE, retain_color_class = NULL, retain_selections = TRUE, tab_accessible = FALSE, debugger = FALSE) {

  table_id = "get_dt_id_from_table(table);"
  out <- c(
    # Create the props object
    "let props = new dt_props(table);"
  )
  if (debugger) {
    out <- c(out, "debugger;")
  }
  if (page_input) {
    out <- c(out, UU::glue_js("
    table.on('page.dt', () => {
      get_dt_props(table).shinyPage();
      return table.page();
    });"))
  }
  lines_on_draw <- c(paste0("var id = ", table_id, ";"), "var table_api = $(id).DataTable()")

  retain_on_draw <- c(
    "search_icon",
    "filter_placeholders",
    "retain_policy_color"
  )

  features <-
    rlang::env_get_list(
      environment(),
      nms = c(
        "search_icon",
        "filter_placeholders",
        "tab_accessible"
      )
    )
  feature_nms <- names(features)
  for (i in seq_along(features)) {
    if (features[[i]]) {
      call <- glue::glue("dt_{feature_nms[i]}(id);")
      if (feature_nms[i] %in% retain_on_draw) {
        # Set placeholders on raw event listener
        lines_on_draw <- c(lines_on_draw, call)
      }
      # Set placeholders on initial render
      out <- c(out, call)
    }
  }

  if (retain_color) {
    stopifnot("`retain_color_class` must be a character" = is.character(retain_color_class))
    # Create the call using the class provided
    call <- UU::glue_js("dt_retain_color(id, '*{retain_color_class}*');")
    # Add to on draw
    lines_on_draw <- c(
      lines_on_draw,
      call
    )
    # Add to initial render
    out <- c(
      out,
      call
    )
  }

  if (!retain_selections) {
    lines_on_draw <- c(lines_on_draw, "table_api.rows().deselect();")
  }
  out <- c(out, UU::glue_js("
       table.on('draw.dt', () => {
         *{glue::glue_collapse(lines_on_draw, sep = '\n')}*
       })")
  )


  if (pageLength_input) {
    out <- c(out,
             UU::glue_js("table.on('length.dt', (e, settings, len) => {
               get_dt_props(table).shinyPageLength()


               return len;
             })")
             )
  }
  out <- c(out, purrr::list_c(rlang::dots_list(...), ptype = character()))
  return(DT::JS(c(out, "return table;")))
}
